apiVersion: v2 # K8S related
name: nginx-1
version: "0.0.3" # This is chart version
appVersion: "1.29-trixie" # This is application version like catalogue version
description: "Installing 1.29.8 version"